### ISSUE TITLE
Result for heterozygous snps varies with the size of input vcf file

### ISSUE THREAD

**Issue by tojojames** [abl0719/ASElux#2]
If I give a vcf file with 3199320 variants (chr 1-22) I get an output file with results for 1513 alleles. If I give a smaller vcf file with 250827 variants (eg. only chr1 of vcf file) I get result close ~1000 alleles and it is clearly more alleles coming from chr 1. 
In that case if I split the larger vcf file into small ones, and aggregate in a second stage I get larger output. I am not sure why the results varies based on the size of the input vcf file though it comes from the same sample. I am working on the phased genotyped data. 

Any information or workaround will be helpful. I can send a test data if you are interested to confirm this issue. / Thanks

Example code for larger vcf file
ASElux align --fq --pe --readLen 75 --index complete --vcf N000370_deCode_RNAseq_chrAll.phased.impute2_haps_genes_MAF05_filter.vcf  --seqFiles 20408_AD0MFNACXX/P64.3_120408_AD0MFNACXX_5_B_index1_1.fastq 120408_AD0MFNACXX/P64.3_120408_AD0MFNACXX_5_B_index1_2.fastq --out N000370_deCode_impuMAF0.5_rc.txt

**Comment by abl0719** [comment]
Hi,

ASElux only counts the uniquely aligned reads. When a read is mapped to several chromosomes, the read would be ignored due to multi-alignment. Although ASElux has a static index which covers most of the genome, it also uses the vcf file to build the dynamic index to improve the alignment accuracy. Thus, when you use only part of the known genotype information, some potential multi-aligned reads might be counted as uniquely aligned.

Moreover, if you filter out the SNPs having very low coverage (for example, SNPs having < 20 reads), the outcome from large or small vcf files should be much more similar to each other. Thus, I would suggest using one vcf file that contains all the known genotype data for the best accuracy, and filter out the very low covered SNPs in the following analysis.

I hope this solves your problem. 

Thanks,
Zong

**Comment by tojojames** [comment]
Thank you for the quick reply :)

Does it mean that it will ignore all the reads that map to a region where SNPs  are close by (less than 75bp+75bp+ insert size + overlap)? I just want to get a sense about how you incorporate the number of mismatches allowed in each read in addition to the SNP mismatches in a smaller region.

A second question, have you done any comparison with Phaser https://github.com/secastel/phaser
I was interested in running phaser in the initial step to select the heterozygous snps with allelic imbalance(AI) and then run ASElux (align) at those AI marked regions.Can you think about any potential mapping bias that arise from this combination.
Thanks!
