### ISSUE TITLE
Error building index

### ISSUE THREAD

**Issue by inti** [abl0719/ASElux#4]
Hi, i am trying to use ASElux on Bombus terrestris data. I downloaded teh ref genome and gtf annoation from the esembl database. I am geeting the following error

```
../../app/ASElux/bin/ASElux build --gtf gtf/Bombus_terrestris.Bter_1.0.39.gtf --ref dna/Bombus_terrestris.Bter_1.0.dna.toplevel.fa --out test_aselux
Building static index...
Anootation finished...
annotation created...
Assertion failed: ((0 <= fs) && (0 < n) && (1 <= k)), function sais_main, file src/SuffixArray.cpp, line 358.
Abort trap: 6
```

Help much welcomed! 

I run the demo and it runs fine ... Do you think you can get the data from the Ensebmbl DB to reproduce the error?

Thanks in advance

**Comment by inti** [comment]
It seems the problem is generated by the ref genome having string after the fasta’s sequences header. For example `>seq` Works find but `>seq some other information` does not. 
It may be worth to check that since many genome files are distributed with additional information on the fasta header line.

**Comment by abl0719** [comment]
Hi inti,

Thank you for the feed back. Since there is no guarantee about how spaces are used in fasta files, ASElux takes whatever after ">" as the name of each chromosome. In your case, the chromosome names in the gtf file don't match the fasta file which caused the problem. We will consider providing an option to only use the characters between ">" and " " as the chromosome names in the future.

Thanks,
Zong
